name: Release Notes
run-name: ${{ github.actor }} is comparing the Release Notes

on:
  workflow_dispatch:
  push:
  # push:
  #   paths:
  #   - .changelog/**
  #   - CHANGELOG.md
  #   - pyproject.yml

jobs:

  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
      with:
        # `towncrier check` runs `git diff --name-only origin/main...`, which
        # needs a non-shallow clone.
        fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install Towncrier
      run: |
        pip install towncrier
    - name: Check for presence of a Change Log fragment (only PRs)
      run: |
        towncrier check --compare-with origin/${{ github.base_ref }}
