name: Release Notes
run-name: ${{ github.actor }} is generating the Release Notes.

on:
  workflow_dispatch:
  push:
    paths:
    - changes/**
    - pyproject.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Check for new CHANGELOG fragements
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
        towncrier check --compare-with origin/${BASE_BRANCH}
