name: Release Notes
run-name: ${{ github.actor }} is comparing the Release Notes

on:
  workflow_dispatch:
  push:
    paths:
    - .changelog/**
    - CHANGELOG.md
    - pyproject.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Check for presence of a Change Log fragment (only PRs)
      run: |
        git fetch --no-tags
        towncrier check
